// SPDX-License-Identifier: Apache-2.0
// Generated by tools/generate-catalog.mjs from data/catalog.json. Do not edit by hand.
// Source: minipro a8efaedc236c1d9718bd28299dfbb99536b010ff, infoic.xml INFOIC2PLUS (XGPro V12.90).

const model = @import("../core/model.zig");
const schema = @import("schema.zig");

const at28c64b_dip28_aliases = [_][]const u8{
    "AT28C64B",
    "AT28C64B@DIP28",
    "AT28C64B-15PU",
};
const at28c64b_dip28_programmers = [_]model.Programmer{
    .t48,
};

const m27c64a_dip28_aliases = [_][]const u8{
    "M27C64A",
    "M27C64A@DIP28",
};
const m27c64a_dip28_programmers = [_]model.Programmer{
    .t48,
};

pub const devices = [_]schema.DeviceRecord{
    .{
        .canonical_name = "AT28C64B@DIP28",
        .aliases = &at28c64b_dip28_aliases,
        .programmers = &at28c64b_dip28_programmers,
        .chip_type = .memory,
        .protocol_id = 0x7,
        .variant = 0x4126,
        .voltages_raw = 0x200,
        .chip_info = 0,
        .pin_map = 0x13,
        .data_memory_size = 0,
        .data_memory2_size = 0,
        .page_size = 64,
        .pulse_delay = 10000,
        .code_memory_size = 8192,
        .package_details_raw = 0x1c000000,
        .read_buffer_size = 512,
        .write_buffer_size = 128,
        .flags_raw = 0xc010,
        .can_erase = true,
        .blank_value = 0xff,
    },
    .{
        .canonical_name = "M27C64A@DIP28",
        .aliases = &m27c64a_dip28_aliases,
        .programmers = &m27c64a_dip28_programmers,
        .chip_type = .memory,
        .protocol_id = 0x7,
        .variant = 0x3313,
        .voltages_raw = 0x4000,
        .chip_info = 0x6,
        .pin_map = 0x15,
        .data_memory_size = 0,
        .data_memory2_size = 0,
        .page_size = 0,
        .pulse_delay = 1000,
        .code_memory_size = 8192,
        .package_details_raw = 0x1c000000,
        .read_buffer_size = 512,
        .write_buffer_size = 128,
        .flags_raw = 0x68,
        .can_erase = false,
        .chip_id = 0x9b08,
        .chip_id_bytes_count = 2,
        .blank_value = 0xff,
    },
};
