// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/generate-catalog.mjs from data/catalog.json. Do not edit by hand.

const model = @import("../core/model.zig");
const schema = @import("schema.zig");

const at28c64b_dip28_aliases = [_][]const u8{
    "AT28C64B",
    "AT28C64B@DIP28",
    "AT28C64B-15PU",
};
const at28c64b_dip28_programmers = [_]model.Programmer{
    .t48,
    .t56,
};

const m27c64a_dip28_aliases = [_][]const u8{
    "M27C64A",
    "M27C64A@DIP28",
    "27C64",
};
const m27c64a_dip28_programmers = [_]model.Programmer{
    .t48,
    .t56,
};

const w25q32jv_soic8_aliases = [_][]const u8{
    "W25Q32JV",
    "W25Q32JV@SOIC8",
    "W25Q32",
};
const w25q32jv_soic8_programmers = [_]model.Programmer{
    .t48,
    .t56,
};

pub const devices = [_]schema.DeviceRecord{
    .{
        .canonical_name = "AT28C64B@DIP28",
        .aliases = &at28c64b_dip28_aliases,
        .programmers = &at28c64b_dip28_programmers,
        .chip_type = .memory,
        .protocol_id = 0x7,
        .variant = 0x0,
        .voltages_raw = 0x200,
        .chip_info = 0,
        .pin_map = 0x14,
        .data_memory_size = 0,
        .data_memory2_size = 0,
        .page_size = 64,
        .pulse_delay = 10000,
        .code_memory_size = 8192,
        .package_details_raw = 0x1c000000,
        .read_buffer_size = 512,
        .write_buffer_size = 128,
        .flags_raw = 0x30,
    },
    .{
        .canonical_name = "M27C64A@DIP28",
        .aliases = &m27c64a_dip28_aliases,
        .programmers = &m27c64a_dip28_programmers,
        .chip_type = .memory,
        .protocol_id = 0x7,
        .variant = 0x0,
        .voltages_raw = 0x200,
        .chip_info = 0,
        .pin_map = 0x14,
        .data_memory_size = 0,
        .data_memory2_size = 0,
        .page_size = 64,
        .pulse_delay = 10000,
        .code_memory_size = 8192,
        .package_details_raw = 0x1c000000,
        .read_buffer_size = 512,
        .write_buffer_size = 128,
        .flags_raw = 0x30,
        .blank_value = 0xff,
    },
    .{
        .canonical_name = "W25Q32JV@SOIC8",
        .aliases = &w25q32jv_soic8_aliases,
        .programmers = &w25q32jv_soic8_programmers,
        .chip_type = .memory,
        .protocol_id = 0x3,
        .variant = 0x0,
        .voltages_raw = 0x100,
        .chip_info = 0,
        .pin_map = 0x8,
        .data_memory_size = 0,
        .data_memory2_size = 0,
        .page_size = 256,
        .pulse_delay = 0,
        .code_memory_size = 4194304,
        .package_details_raw = 0x8000000,
        .read_buffer_size = 512,
        .write_buffer_size = 256,
        .flags_raw = 0x30,
        .chip_id = 0xef4016,
        .chip_id_bytes_count = 3,
    },
};
