complete -c minipro-zig -s h -l help -d 'Show help'
complete -c minipro-zig -s V -l version -d 'Show version'
complete -c minipro-zig -l db -r -d 'SQLite database path'
complete -c minipro-zig -s q -l programmer -x -a 'auto tl866a tl866ii t48 t56 t76' -d 'Programmer family'
complete -c minipro-zig -l json -d 'Emit JSON where supported'
complete -c minipro-zig -l verbose -d 'Print extra diagnostics'
complete -c minipro-zig -l quiet -d 'Reduce nonessential output'

complete -c minipro-zig -n '__fish_use_subcommand' -a programmer -d 'Programmer commands'
complete -c minipro-zig -n '__fish_use_subcommand' -a db -d 'Database commands'
complete -c minipro-zig -n '__fish_use_subcommand' -a device -d 'Device database commands'
complete -c minipro-zig -n '__fish_use_subcommand' -a chip -d 'Chip operation commands'
complete -c minipro-zig -n '__fish_use_subcommand' -a logic -d 'Logic IC commands'

complete -c minipro-zig -n '__fish_seen_subcommand_from programmer' -a 'list detect info'
complete -c minipro-zig -n '__fish_seen_subcommand_from db' -a 'import stats query'
complete -c minipro-zig -n '__fish_seen_subcommand_from device' -a 'list search info'
complete -c minipro-zig -n '__fish_seen_subcommand_from chip' -a 'read read-id autodetect blank verify erase write protect unprotect'
complete -c minipro-zig -n '__fish_seen_subcommand_from logic' -a test

complete -c minipro-zig -l infoic -r -d 'Upstream infoic.xml path'
complete -c minipro-zig -l logicic -r -d 'Upstream logicic.xml path'
complete -c minipro-zig -l algorithms -r -d 'Optional algorithm.xml path'
complete -c minipro-zig -l out -r -d 'Output path'
complete -c minipro-zig -l in -r -d 'Input path'
complete -c minipro-zig -l device -r -d 'Device name'
complete -c minipro-zig -l format -x -a 'bin ihex srec config jedec' -d 'File format'
complete -c minipro-zig -l memory -x -a 'code data user' -d 'Memory kind'
complete -c minipro-zig -l package -x -a '8 16' -d 'SPI package size'
complete -c minipro-zig -l execute -d 'Access hardware'
complete -c minipro-zig -l confirm-destructive -r -d 'Confirm destructive operation'

complete -c minipro-zig -s Q -l query_supported -d 'List programmer families'
complete -c minipro-zig -s k -l presence_check -d 'Detect programmer'
complete -c minipro-zig -s p -r -d 'Legacy device selector'
complete -c minipro-zig -s r -r -d 'Legacy read file'
complete -c minipro-zig -s w -r -d 'Legacy write file'
complete -c minipro-zig -s m -r -d 'Legacy verify file'
complete -c minipro-zig -s E -d 'Legacy erase'
complete -c minipro-zig -s P -d 'Legacy protect'
complete -c minipro-zig -s u -d 'Legacy unprotect'
complete -c minipro-zig -s D -d 'Legacy read ID'
complete -c minipro-zig -s b -d 'Legacy blank check'
complete -c minipro-zig -s T -d 'Legacy logic test'
complete -c minipro-zig -s a -x -a '8 16' -d 'Legacy autodetect package size'
