#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0

import { Buffer } from "node:buffer";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = new Set(process.argv.slice(2));
const checkOnly = args.has("--check");
const sourcePath = resolve(repoRoot, "data/catalog.json");
const outputPath = resolve(repoRoot, "src/catalog/generated.zig");

const input = JSON.parse(readFileSync(sourcePath, "utf8"));
const generated = generate(input);

if (checkOnly) {
  const existing = readFileSync(outputPath, "utf8");
  if (existing !== generated) {
    console.error("src/catalog/generated.zig is out of date. Run `pnpm run generate:catalog`.");
    process.exit(1);
  }
} else {
  writeFileSync(outputPath, generated);
}

function generate(catalog) {
  if (!catalog || !Array.isArray(catalog.devices)) {
    throw new Error("catalog must contain a devices array");
  }

  const out = [];
  out.push("// SPDX-License-Identifier: Apache-2.0");
  out.push("// Generated by tools/generate-catalog.mjs from data/catalog.json. Do not edit by hand.");
  out.push("");
  out.push('const model = @import("../core/model.zig");');
  out.push('const schema = @import("schema.zig");');
  out.push("");

  const names = new Set();
  const records = catalog.devices.map((device, index) => {
    validateDevice(device, index);
    const name = symbolName(device.canonicalName);
    if (names.has(name)) throw new Error(`duplicate generated symbol ${name}`);
    names.add(name);
    writeStringArray(out, `${name}_aliases`, device.aliases);
    writeProgrammerArray(out, `${name}_programmers`, device.programmers);
    if (device.t56AlgorithmHex || device.t56AlgorithmBase64) {
      writeByteArray(out, `${name}_t56_algorithm`, decodeAlgorithm(device));
    }
    out.push("");
    return { name, device };
  });

  out.push("pub const devices = [_]schema.DeviceRecord{");
  for (const { name, device } of records) {
    out.push("    .{");
    field(out, "canonical_name", zigString(device.canonicalName));
    field(out, "aliases", `&${name}_aliases`);
    field(out, "programmers", `&${name}_programmers`);
    field(out, "chip_type", `.${device.chipType}`);
    field(out, "protocol_id", zigNumber(device.protocolId));
    field(out, "variant", zigNumber(device.variant));
    field(out, "voltages_raw", zigNumber(device.voltagesRaw));
    field(out, "chip_info", zigNumber(device.chipInfo));
    field(out, "pin_map", zigNumber(device.pinMap));
    field(out, "data_memory_size", zigNumber(device.dataMemorySize));
    field(out, "data_memory2_size", zigNumber(device.dataMemory2Size));
    field(out, "page_size", zigNumber(device.pageSize));
    field(out, "pulse_delay", zigNumber(device.pulseDelay));
    field(out, "code_memory_size", zigNumber(device.codeMemorySize));
    field(out, "package_details_raw", zigNumber(device.packageDetailsRaw));
    field(out, "read_buffer_size", zigNumber(device.readBufferSize));
    field(out, "write_buffer_size", zigNumber(device.writeBufferSize));
    field(out, "flags_raw", zigNumber(device.flagsRaw));
    if (device.canAdjustClock != null) field(out, "can_adjust_clock", String(Boolean(device.canAdjustClock)));
    if (device.chipId != null) field(out, "chip_id", zigNumber(device.chipId));
    if (device.chipIdBytesCount != null) field(out, "chip_id_bytes_count", zigNumber(device.chipIdBytesCount));
    if (device.blankValue != null) field(out, "blank_value", zigNumber(device.blankValue));
    if (device.t56AlgorithmHex || device.t56AlgorithmBase64) field(out, "t56_algorithm", `&${name}_t56_algorithm`);
    out.push("    },");
  }
  out.push("};");
  out.push("");
  return out.join("\n");
}

function validateDevice(device, index) {
  const label = `devices[${index}]`;
  requiredString(device, "canonicalName", label);
  requiredArray(device, "aliases", label);
  requiredArray(device, "programmers", label);
  requiredString(device, "chipType", label);
  for (const key of [
    "protocolId",
    "variant",
    "voltagesRaw",
    "chipInfo",
    "pinMap",
    "dataMemorySize",
    "dataMemory2Size",
    "pageSize",
    "pulseDelay",
    "codeMemorySize",
    "packageDetailsRaw",
    "readBufferSize",
    "writeBufferSize",
    "flagsRaw",
  ]) {
    parseNumber(device[key], `${label}.${key}`);
  }
  for (const programmer of device.programmers) {
    if (programmer !== "t48" && programmer !== "t56") throw new Error(`${label}.programmers contains unsupported programmer ${programmer}`);
  }
  if (device.programmers.includes("t56") && !device.t56AlgorithmHex && !device.t56AlgorithmBase64) {
    throw new Error(`${label}.programmers includes t56 but no T56 algorithm payload is present`);
  }
  if (device.t56AlgorithmHex && device.t56AlgorithmBase64) {
    throw new Error(`${label} must use only one T56 algorithm encoding`);
  }
}

function requiredString(object, key, label) {
  if (typeof object[key] !== "string" || object[key].length === 0) throw new Error(`${label}.${key} must be a non-empty string`);
}

function requiredArray(object, key, label) {
  if (!Array.isArray(object[key]) || object[key].length === 0) throw new Error(`${label}.${key} must be a non-empty array`);
}

function parseNumber(value, label) {
  if (typeof value === "number") {
    if (!Number.isInteger(value) || value < 0) throw new Error(`${label} must be a non-negative integer`);
    return value;
  }
  if (typeof value === "string" && /^0x[0-9a-f]+$/iu.test(value)) return Number.parseInt(value.slice(2), 16);
  if (typeof value === "string" && /^[0-9]+$/u.test(value)) return Number.parseInt(value, 10);
  throw new Error(`${label} must be a non-negative integer or hex string`);
}

function zigNumber(value) {
  const parsed = parseNumber(value, "number");
  return typeof value === "string" && value.toLowerCase().startsWith("0x") ? `0x${parsed.toString(16)}` : String(parsed);
}

function symbolName(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/gu, "_").replace(/^_+|_+$/gu, "");
}

function writeStringArray(out, name, values) {
  out.push(`const ${name} = [_][]const u8{`);
  for (const value of values) out.push(`    ${zigString(value)},`);
  out.push("};");
}

function writeProgrammerArray(out, name, values) {
  out.push(`const ${name} = [_]model.Programmer{`);
  for (const value of values) out.push(`    .${value},`);
  out.push("};");
}

function writeByteArray(out, name, bytes) {
  if (bytes.length === 0) throw new Error(`${name} must not be empty`);
  out.push(`const ${name} = [_]u8{`);
  for (let offset = 0; offset < bytes.length; offset += 12) {
    const chunk = bytes.subarray(offset, offset + 12);
    out.push(`    ${Array.from(chunk, (byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(", ")},`);
  }
  out.push("};");
}

function decodeAlgorithm(device) {
  if (device.t56AlgorithmHex) {
    const normalized = device.t56AlgorithmHex.replace(/\s+/gu, "");
    if (normalized.length % 2 !== 0 || /[^0-9a-f]/iu.test(normalized)) throw new Error(`${device.canonicalName} has invalid t56AlgorithmHex`);
    return Buffer.from(normalized, "hex");
  }
  return Buffer.from(device.t56AlgorithmBase64, "base64");
}

function field(out, key, value) {
  out.push(`        .${key} = ${value},`);
}

function zigString(value) {
  return JSON.stringify(value);
}
